# Based on
# -https://github.com/marketplace/actions/setup-go-environment

name: go-test.yaml

on: [push]

env:
  SENZING_ACCEPT_EULA: I_ACCEPT_THE_SENZING_EULA

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.19"]
    name: Go ${{ matrix.go }} sample
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - run: env
      - run: echo ${SENZING_ACCEPT_EULA}
      - run: wget -qO /tmp/senzingrepo_1.0.1-1_amd64.deb https://senzing-production-apt.s3.amazonaws.com/senzingrepo_1.0.1-1_amd64.deb
      - run: sudo apt-get -y install /tmp/senzingrepo_1.0.1-1_amd64.deb
      - run: sudo apt-get update
      - run: sudo apt-get -y install senzingapi-runtime
      - run: mkdir /tmp/sqlite
      - run: cp testdata/sqlite/G2C.db /tmp/sqlite/G2C.db
      - run: go test -v -p 1 ./...
